### ISSUE TITLE
Setup script: npm throws errors

### ISSUE THREAD

**Issue by erNail** [ConsenSys/QuorumNetworkManager#31]
Hi, i'm trying to use the network manager in the vagrant box provided in the [quorum-examples](https://github.com/jpmorganchase/quorum-examples). 
When running the `setup.sh`, these errors are thrown and execution stops: 

```
2017-08-29 10:38:05 (2.56 MB/s) - ‘ubuntu1604.zip’ saved [6724725/6724725]

Archive:  ubuntu1604.zip
   creating: ubuntu1604/
  inflating: ubuntu1604/constellation-enclave-keygen
  inflating: ubuntu1604/constellation-node
Cloning into 'quorum-genesis'...
remote: Counting objects: 7, done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 7
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
npm WARN /home/ubuntu/shared/quorum-genesis/node_modules/ansi-regex is not a child of /usr/lib
npm ERR! path /home/ubuntu/shared/quorum-genesis/node_modules/ansi-regex
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/ubuntu/shared/quorum-genesis/node_modules/ansi-regex' -> '/home/ubuntu/shared/quorum-genesis/node_modules/.ansi-regex.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-29T10_38_16_544Z-debug.log
Cloning into 'QuorumNetworkManager'...
remote: Counting objects: 746, done.
remote: Total 746 (delta 0), reused 0 (delta 0), pack-reused 746
Receiving objects: 100% (746/746), 202.85 KiB | 303.00 KiB/s, done.
Resolving deltas: 100% (483/483), done.
Checking connectivity... done.
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/debris/bignumber.js.git /root/.npm/_cacache/tmp/git-clone-a4d03ef2
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-a4d03ef2': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-29T10_38_22_235Z-debug.log
root@ubuntu-xenial:/home/ubuntu/shared/quorum-network-manager#
```

When trying to run `node index.js` i get the following error:

```
root@ubuntu-xenial:/home/ubuntu/shared/quorum-network-manager/QuorumNetworkManager# node index.js
module.js:491
    throw err;
    ^

Error: Cannot find module 'prompt'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/shared/quorum-network-manager/QuorumNetworkManager/index.js:1:76)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by coeniebeyers** [comment]
Hi! I've not tried running the QNM from within vagrant, however it should be possible.

Note that the setup script will attempt to set up everything you'll need. This means you'll need a clean VM to work from otherwise there will be clashes.

Your second issue (running `node index.js` fails) is simply because the prompt module hasn't been installed yet.

**Comment by erNail** [comment]
I can confirm that there is a problem with the vagrant box provided in the [quorum-examples](https://github.com/jpmorganchase/quorum-examples). 
When using a clean vagrant box (in my case [ubuntu/xenial64](https://app.vagrantup.com/ubuntu/boxes/xenial64)), running `setup.sh` doesn't throw any errors. 
Thanks for your help.
