### ISSUE TITLE
Error: "constellation-enclave-keygen: not found" while running node index.js

### ISSUE THREAD

**Issue by erNail** [ConsenSys/QuorumNetworkManager#32]
Hi,

after successfully running `setup.sh` in my clean vagrant box i'm trying to run `node index.js`. The following errors are thrown:

```
root@ubuntu-xenial:/home/ubuntu/QuorumNetworkManager# node index.js
Trying to get public ip address, please wait a few seconds...
Welcome! Before we get started, please enter the IP address other nodes will use to connect to this node.
prompt: localIpAddress:  (84.133.61.171) 10.10.10.116
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  2
Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  1
[*] Starting new network...
Please enter the configuration for this network:
prompt: numberOfBlockVoters:  2
prompt: numberOfBlockMakers:  2
prompt: minimumTimeBetweenBlocks:  10
prompt: maximumTimeBetweenBlocks:  20
prompt: minimumNumberOfRequiredVoters:  2

Select which block makers to use
Note that the first address will be used on this node
Please enter an address (starting with 0x) or enter a 1 to generate an address to use
prompt: address0:  1
prompt: address1:  1

Select which block voters to use
Note that the first address will be used on this node
Please enter an address (starting with 0x) or enter a 1 to generate an address to use
prompt: address0:  1
prompt: address1:  1
ERROR: /bin/sh: 1:
ERROR /bin/sh: 1:
ERROR: constellation-enclave-keygen: not found
/home/ubuntu/QuorumNetworkManager/node_modules/async/dist/async.js:903
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /home/ubuntu/QuorumNetworkManager/node_modules/async/dist/async.js:903:32
    at /home/ubuntu/QuorumNetworkManager/node_modules/async/dist/async.js:2491:13
    at /home/ubuntu/QuorumNetworkManager/node_modules/async/dist/async.js:2552:17
    at Socket.<anonymous> (/home/ubuntu/QuorumNetworkManager/constellation.js:28:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at Pipe.onread (net.js:585:20)
```

**Comment by coeniebeyers** [comment]
Hi! I'm assuming that `$ which constellation-enclave-keygen` doesn't return anything?

Can you check/paste the last few lines of your  `.bashrc` ? It should contain something like
```
PATH=$PATH:/home/ubuntu/shared/constellation/ubuntu1604
```

**Comment by erNail** [comment]
You're right, `$ which constellation-enclave-keygen` doesn't return anything.

These are the last lines of my `~/.bashrc`:

```
PATH=$PATH:/home/ubuntu/workspace/quorum/build/bin
PATH=$PATH:/home/ubuntu/workspace/ubuntu1604
PATH=$PATH:/home/ubuntu/workspace/quorum/build/bin
PATH=$PATH:/home/ubuntu/workspace/ubuntu1604
PATH=$PATH:/home/ubuntu/workspace/quorum/build/bin
PATH=$PATH:/home/ubuntu/workspace/constellation/ubuntu1604
PATH=$PATH:/home/ubuntu/workspace/quorum/build/bin
PATH=$PATH:/home/ubuntu/workspace/constellation/ubuntu1604
```

**Comment by erNail** [comment]
When installing everything manually, and putting all binaries in `/usr/bin`, running `constellation-enclave-keygen` is working. Seems like there is a problem with the PATH when running `setup.sh`.

**Comment by coeniebeyers** [comment]
Hi! I think that might be part of the problem. First, let's find out where the constellation binaries live (atleast the ones we want to use). Please do a `ls /home/ubuntu/workspace/constellation/ubuntu1604` and check the output for `constellation-enclave-keygen` and  `constellation-node`. Next, update your `~/.bashrc` to only contain:
```
PATH=$PATH:/home/ubuntu/workspace/quorum/build/bin
PATH=$PATH:/home/ubuntu/workspace/constellation/ubuntu1604
```
You should be able to clean up the contents of the unused directories. Remember to `source ~/.bashrc` before changes will be reflected.

Next, I notice no `go` path being set there, what is the output of `which go`?

**Comment by erNail** [comment]
I've just set up a new clean vagrant box and installed everything with the `setup.sh`. Now, when i'm creating a new Network with `node index.js`, there are no errors at all. 

I've only did one thing different: I ran `$ sudo ./setup.sh`. Not sure if this was the cause for all the errors, but maybe you should consider updating your `README.md` to run `./setup.sh` with sudo.

Again, thanks for the help :).
