### ISSUE TITLE
Can't join created Quorum network: IPC Connection Error

### ISSUE THREAD

**Issue by erNail** [ConsenSys/QuorumNetworkManager#33]
Hi,

after starting a new network i try to join it (in the same vm, in the same session). However, a connection error is thrown. Below is the full console output/input:

```
root@vagrant:/home/vagrant/QuorumNetworkManager# node index.js
Trying to get public ip address, please wait a few seconds...
Welcome! Before we get started, please enter the IP address other nodes will use to connect to this node.
prompt: localIpAddress:  (20.143.91.92) 10.10.10.116
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  2
Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  1
[*] Starting new network...
Please enter the configuration for this network:
prompt: numberOfBlockVoters:  3
prompt: numberOfBlockMakers:  2
prompt: minimumTimeBetweenBlocks:  10
prompt: maximumTimeBetweenBlocks:  20
prompt: minimumNumberOfRequiredVoters:  2

Select which block makers to use
Note that the first address will be used on this node
Please enter an address (starting with 0x) or enter a 1 to generate an address to use
prompt: address0:  1
prompt: address1:  1

Select which block voters to use
Note that the first address will be used on this node
Please enter an address (starting with 0x) or enter a 1 to generate an address to use
prompt: address0:  1
prompt: address1:  1
prompt: address2:  1
[*] Creating genesis config...
[*] Starting communication network...
[*] New communication network started
[*] New network started
Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  6
Enode details:

 enode://9443bd2c5ccc5978831088755491417fe0c3866537b5e9638bcb6ad34cb9bcc58a9338bb492590ff200a54b43a6a03e4a7e33fa111d0a7f6b7192d1ca050f300@10.10.10.116:50000

Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  2

In order to join an existing network, please enter either:
1) the ip address of the coordinating node
2) a communication network enode of any other node on the network
prompt: connection:  10.10.10.116
Please select an option:
0) Join the network as a block maker and block voter
1) Join the network as a block maker
2) Join the network as a block voter
3) Join the network as a participant
prompt: option:  1
[*] Joining communication network...
IPC Connection Error { Error: connect ENOENT ./CommunicationNode/geth.ipc
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: './CommunicationNode/geth.ipc' }
ERROR: Error: CONNECTION ERROR: Couldn't connect to node on IPC.
    at Object.InvalidConnection (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/errors.js:28:16)
    at IpcProvider._timeout (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/ipcprovider.js:150:48)
    at Socket.<anonymous> (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/ipcprovider.js:38:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[*] Communication network started
[*] Joining existing quorum network...
Please enter the configuration for this network:
prompt: minimumTimeBetweenBlocks:  10
prompt: maximumTimeBetweenBlocks:  20

Select which block maker to use
Please enter either:
1) an address (starting with 0x)
2) a 1 to generate an address to use
3) a 0 to not participate in this role
prompt: address:  1
generating new address...
Please use 0xf694a147b2a138f0b006f579700046162cb5fc15 as your block maker address
[*] Requesting genesis block config. This will block until the other node is online
received genesis config
1[*] New network started
Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  IPC Connection Error { Error: connect ENOENT ./Blockchain/geth.ipc
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: './Blockchain/geth.ipc' }
```

Is there something i'm doing wrong ?

**Comment by coeniebeyers** [comment]
Hi! You will need to start a new VM for your subsequent nodes. That is, the QNM currently designed to run one node per VM/machine. Trying to start another node from the same VM will result in port conflicts etc.as well as the above.

**Comment by erNail** [comment]
Thanks, but it's still not working. In my first VM, i did the following:

```
root@vagrant:/home/vagrant/QuorumNetworkManager# node index.js
Trying to get public ip address, please wait a few seconds...
Welcome! Before we get started, please enter the IP address other nodes will use to connect to this node.
prompt: localIpAddress:  (84.10.10.50) 10.10.10.116
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  2
Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  1
[*] Starting new network...
Please enter the configuration for this network:
prompt: numberOfBlockVoters:  2
prompt: numberOfBlockMakers:  1
prompt: minimumTimeBetweenBlocks:  10
prompt: maximumTimeBetweenBlocks:  20
prompt: minimumNumberOfRequiredVoters:  1

Select which block makers to use
Note that the first address will be used on this node
Please enter an address (starting with 0x) or enter a 1 to generate an address to use
prompt: address0:  1

Select which block voters to use
Note that the first address will be used on this node
Please enter an address (starting with 0x) or enter a 1 to generate an address to use
prompt: address0:  1
prompt: address1:  1
[*] Creating genesis config...
[*] Starting communication network...
[*] New communication network started
[*] New network started
```

Then, in my second VM, i still get the IPC Error:

```
root@vagrant:/home/vagrant/QuorumNetworkManager# node index.js
Trying to get public ip address, please wait a few seconds...
Welcome! Before we get started, please enter the IP address other nodes will use to connect to this node.
prompt: localIpAddress:  (84.10.10.50) 10.10.10.117
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  2
Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  2

In order to join an existing network, please enter either:
1) the ip address of the coordinating node
2) a communication network enode of any other node on the network
prompt: connection:  10.10.10.116
Please select an option:
0) Join the network as a block maker and block voter
1) Join the network as a block maker
2) Join the network as a block voter
3) Join the network as a participant
prompt: option:  0
[*] Joining communication network...
IPC Connection Error { Error: connect ENOENT ./CommunicationNode/geth.ipc
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: './CommunicationNode/geth.ipc' }
ERROR: Error: CONNECTION ERROR: Couldn't connect to node on IPC.
    at Object.InvalidConnection (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/errors.js:28:16)
    at IpcProvider._timeout (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/ipcprovider.js:150:48)
    at Socket.<anonymous> (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/ipcprovider.js:38:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[*] Communication network started
[*] Joining existing quorum network...
Please enter the configuration for this network:
prompt: minimumTimeBetweenBlocks:  10
prompt: maximumTimeBetweenBlocks:  20

Select which block maker to use
Please enter either:
1) an address (starting with 0x)
2) a 1 to generate an address to use
3) a 0 to not participate in this role
prompt: address:  1
generating new address...
ERROR: /bin/sh: 1: geth: not found

/home/vagrant/QuorumNetworkManager/joinNewNetwork.js:160
        address = res.addressList[0]
                     ^

TypeError: Cannot read property 'addressList' of null
    at /home/vagrant/QuorumNetworkManager/joinNewNetwork.js:160:22
    at Socket.<anonymous> (/home/vagrant/QuorumNetworkManager/util.js:112:7)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at Pipe.onread (net.js:585:20)
```

The VM's are able to ping each other, so that's not the problem.

**Comment by coeniebeyers** [comment]
Hi! What is the output of `which geth` ? 

This line looks suspect:
```
ERROR: /bin/sh: 1: geth: not found
```

**Comment by coeniebeyers** [comment]
Hi! Can we close this issue?

**Comment by erNail** [comment]
Hi, i don't know what caused the `ERROR: /bin/sh: 1: geth: not found`, but it's gone now. However, i'm still getting the ipc error:

```
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  2
Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  2

In order to join an existing network, please enter either:
1) the ip address of the coordinating node
2) a communication network enode of any other node on the network
prompt: connection:  10.40.93.117
Please select an option:
0) Join the network as a block maker and block voter
1) Join the network as a block maker
2) Join the network as a block voter
3) Join the network as a participant
prompt: option:  0
[*] Joining communication network...
true
[*] Communication network started
[*] Joining existing quorum network...
Please enter the configuration for this network:
prompt: minimumTimeBetweenBlocks:  10
prompt: maximumTimeBetweenBlocks:  20

Select which block maker to use
Please enter either:
1) an address (starting with 0x)
2) a 1 to generate an address to use
3) a 0 to not participate in this role
prompt: address:  0x8b56e63388d6df8c8fe713e429eea8b1effc0156
Please use 0x8b56e63388d6df8c8fe713e429eea8b1effc0156 as your block maker address

Select which block voter to use
Please enter either:
1) an address (starting with 0x)
2) a 1 to generate an address to use
3) a 0 to not participate in this role
prompt: address:  0x0991bda17124a72b7af13e8169eb1bfe194774e9
Please use 0x0991bda17124a72b7af13e8169eb1bfe194774e9 as your block voter address
[*] Requesting genesis block config. This will block until the other node is online
received genesis config
[*] Started node as BM + BV
[*] New network started
Please select an option below:
1) Start a new Quorum network [WARNING: this clears everything]
2) Join an existing Quorum network, first time joining this network. [WARNING: this clears everything]
3) Reconnect to the previously connected network
4) Enable network statistics
5) killall geth constellation-node
6) Display communication network connection details
0) Quit
prompt: option:  IPC Connection Error { Error: connect ECONNREFUSED ./Blockchain/geth.ipc
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: './Blockchain/geth.ipc' }
IPC Connection Error { Error: connect ECONNREFUSED ./Blockchain/geth.ipc
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: './Blockchain/geth.ipc' }
ERROR: Error: CONNECTION ERROR: Couldn't connect to node on IPC.
    at Object.InvalidConnection (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/errors.js:28:16)
    at IpcProvider._timeout (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/ipcprovider.js:150:48)
    at Socket.<anonymous> (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/ipcprovider.js:38:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/home/vagrant/QuorumNetworkManager/whisperNetwork.js:69
        var enodeResponse = 'response|enode'+nodeInfo.enode
                                                     ^

TypeError: Cannot read property 'enode' of undefined
    at Object.callback (/home/vagrant/QuorumNetworkManager/whisperNetwork.js:69:54)
    at /home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/method.js:142:25
    at Object.<anonymous> (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/requestmanager.js:82:20)
    at IpcProvider._timeout (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/ipcprovider.js:150:40)
    at Socket.<anonymous> (/home/vagrant/QuorumNetworkManager/node_modules/web3_ipc/node_modules/web3/lib/web3/ipcprovider.js:38:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by coeniebeyers** [comment]
Hi! The error you are seeing is because the node/geth isn't running. That means the node quit for some reason, or couldn't start. Can you have a look at what `gethNode.log` contains?

**Comment by erNail** [comment]
This is the `gethnode.log` of the first VM:

```
I0907 11:11:44.057828 ethdb/database.go:81] Allotted 128MB cache and 1024 file handles to /home/vagrant/QuorumNetworkMa$I0907 11:11:44.065797 ethdb/database.go:174] closed db:/home/vagrant/QuorumNetworkManager/Blockchain/geth/chaindata
I0907 11:11:44.066224 node/node.go:179] instance: Geth/v1.5.0-unstable-5dfdecef/linux/go1.7
I0907 11:11:44.066245 ethdb/database.go:81] Allotted 128MB cache and 1024 file handles to /home/vagrant/QuorumNetworkMa$I0907 11:11:44.100674 eth/db_upgrade.go:346] upgrading db log bloom bins
I0907 11:11:44.100750 eth/db_upgrade.go:354] upgrade completed in 79.949µs
I0907 11:11:44.100767 eth/backend.go:177] Protocol Versions: [63 62], Network Id: 91351
I0907 11:11:44.101319 core/blockchain.go:225] Last header: #0 [a4577054…] TD=0
I0907 11:11:44.101334 core/blockchain.go:226] Last block: #0 [a4577054…] TD=0
I0907 11:11:44.101424 core/blockchain.go:227] Fast block: #0 [a4577054…] TD=0
I0907 11:11:44.103061 p2p/server.go:328] Starting Server
I0907 11:11:44.103162 whisper/whisperv2/whisper.go:176] Whisper started
I0907 11:11:44.105342 node/node.go:414] HTTP endpoint opened: http://0.0.0.0:20010
I0907 11:11:44.113208 p2p/server.go:582] Listening on [::]:20000
I0907 11:11:44.113691 node/node.go:344] IPC endpoint opened: /home/vagrant/QuorumNetworkManager/Blockchain/geth.ipc
I0907 11:11:45.156054 cmd/geth/accountcmd.go:189] Unlocked account 05763b440bac56e64451d20ccdf5bc5d75c3d4ca
I0907 11:11:46.514464 cmd/geth/accountcmd.go:189] Unlocked account d8935cfd389066b74fdd14af34c0d0b75ae48a40
I0907 11:11:46.515237 core/quorum/block_voting.go:196] Node configured for block creation: 0xd8935cfd389066b74fdd14af34$I0907 11:11:46.515258 core/quorum/block_voting.go:199] Node configured for block voting: 0x05763b440bac56e64451d20ccdf5$I0907 11:11:57.527262 internal/ethapi/api.go:1246] Tx(3e8de1217e5a5dbf5bfaa1e5d275efd7972edc2422cf064a183831a037554fb6)$I0907 11:12:14.526431 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.107 Mg) in   6.535ms (16.363 Mg/s). #1$I0907 11:12:14.534429 internal/ethapi/api.go:1246] Tx(b63172091efdc31570e50430f0426d60f5b49aaeec190853be1bb90f52b53694)$I0907 11:12:33.529768 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   1.452ms (63.313 Mg/s). #2$I0907 11:12:33.531392 internal/ethapi/api.go:1246] Tx(1317f44ebbb9120fa362e1bb1f98f1912b3b1775ce82e9f6f8baae53fc3103f9)$I0907 11:12:51.532700 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   1.465ms (62.725 Mg/s). #3$I0907 11:12:51.540920 internal/ethapi/api.go:1246] Tx(c2e6b7f745725821da4ae4db29aa8d26ef3fd8b99064a13eb958fea2ae88a4ef)$I0907 11:13:01.542501 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   6.348ms (14.481 Mg/s). #4$I0907 11:13:01.549507 internal/ethapi/api.go:1246] Tx(43e0a9c4d977cfceee0cda96710cec2c8bbb14a0d29fb276e656d78af5da0ae3)$I0907 11:13:11.552666 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   6.335ms (14.511 Mg/s). #5$I0907 11:13:11.560205 internal/ethapi/api.go:1246] Tx(27d8078fc3641ee3d44cd3cd5d19c5b46ad011dad011dc8c9c6bab938f164e0d)$I0907 11:13:22.555994 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   1.744ms (52.701 Mg/s). #6$I0907 11:13:22.564395 internal/ethapi/api.go:1246] Tx(f407214ee7a84a09fad46f20b7ad6248d30e2d27d43ba0168b057d8af0cfe30e)$I0907 11:13:41.559076 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   1.614ms (56.941 Mg/s). #7$I0907 11:13:41.560734 internal/ethapi/api.go:1246] Tx(937ee30997ee2b4ea221eda9a120e622f22491e9f2789d4b145829332e58d8bf)$I0907 11:13:55.561757 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   1.536ms (59.814 Mg/s). #8$I0907 11:13:55.568448 internal/ethapi/api.go:1246] Tx(3fd261f823797a36db003d0e80e43ea235997e43c10fb29607dbe243dffd3813)$I0907 11:14:10.574290 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   9.163ms (10.032 Mg/s). #9$I0907 11:14:10.581477 internal/ethapi/api.go:1246] Tx(e001de787b17d78db3996d1bb3bda0300aeb9f9facbd7da9aa7c3d599106bf96)$I0907 11:14:26.577750 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   1.781ms (51.600 Mg/s). #1$I0907 11:14:26.579430 internal/ethapi/api.go:1246] Tx(5015559ce3ed4757704011889dd36ba30d8f1bcf3ed80410725b8b4c41d18e1d)$I0907 11:14:42.581569 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   2.215ms (41.493 Mg/s). #1$I0907 11:14:42.583631 internal/ethapi/api.go:1246] Tx(a6b7781ac6d0026cc213c4efcfa2084484e6196b08550ed6ef9773384f3c4423)$I0907 11:15:00.594010 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   9.059ms (10.148 Mg/s). #1$I0907 11:15:00.602003 internal/ethapi/api.go:1246] Tx(70725e39e377841a192948f0862d72d235b96a1db78aa72b0dbcd701432f42ea)$I0907 11:15:17.601102 core/blockchain.go:1069] imported 1 blocks,     1 txs (  0.092 Mg) in   4.084ms (22.506 Mg/s). #1$
```

This is the log of the second:

```
I0907 11:17:41.766422 ethdb/database.go:81] Allotted 128MB cache and 1024 file handles to /home/vagrant/QuorumNetworkMa$I0907 11:17:41.775086 ethdb/database.go:174] closed db:/home/vagrant/QuorumNetworkManager/Blockchain/geth/chaindata
I0907 11:17:41.775150 cmd/utils/flags.go:566] WARNING: No etherbase set and no accounts found as default
I0907 11:17:41.775468 node/node.go:179] instance: Geth/v1.5.0-unstable-5dfdecef/linux/go1.7
I0907 11:17:41.775479 ethdb/database.go:81] Allotted 128MB cache and 1024 file handles to /home/vagrant/QuorumNetworkMa$I0907 11:17:41.896731 eth/db_upgrade.go:346] upgrading db log bloom bins
I0907 11:17:41.896800 eth/db_upgrade.go:354] upgrade completed in 72.848µs
I0907 11:17:41.896816 eth/backend.go:177] Protocol Versions: [63 62], Network Id: 91351
I0907 11:17:41.897182 core/blockchain.go:225] Last header: #0 [a4577054…] TD=0
I0907 11:17:41.897193 core/blockchain.go:226] Last block: #0 [a4577054…] TD=0
I0907 11:17:41.897198 core/blockchain.go:227] Fast block: #0 [a4577054…] TD=0
I0907 11:17:41.897624 p2p/server.go:328] Starting Server
I0907 11:17:41.897696 whisper/whisperv2/whisper.go:176] Whisper started
I0907 11:17:41.899104 node/node.go:414] HTTP endpoint opened: http://0.0.0.0:20010
Fatal: Failed to unlock account 0x05763b440bac56e64451d20ccdf5bc5d75c3d4ca (no key for given address or file)
```
