### ISSUE TITLE
New raft nodes 'struggle' to connect to a main node

### ISSUE THREAD

**Issue by bouwerp** [ConsenSys/QuorumNetworkManager#57]
After starting a Raft network, and allowing other nodes to freely connect, the new membership nodes keep blocking ad infinitum. The main node keeps on reporting that the nodes are joining, and frequently encounters errors when the same nodes attempt to join again.

Errors on main node:
```
54.172.1.79 has joined the network with raftID: undefined
54.83.184.40 has joined the network with raftID: 3
addPeer ERROR: Error: node is already in the cluster: enode://e35d909845a4ef89eae527b355e0a11ff8303a2638b33cc1262d5b8030a25a08446f2591b34b53cbba489fa3ceb63b8b8e7f813cdc524aa54f9c9d268bab62b4@54.172.1.79:20000?raftport=40000
    at Object.InvalidResponse (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/errors.js:38:16)
    at /root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/httpprovider.js:122:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
54.172.1.79 has joined the network with raftID: undefined
readline.js:1017
```

The other nodes keep blocking:
```

[*] Requesting existing network membership. This will block until the other node responds
```

The installation was done using `setup.sh`, on Ubuntu 16.04.

**This behaviour occurs when selecting the `3) Join already running raft network [WARNING: this clears everything]` option.**

**Comment by bouwerp** [comment]
Similarly, when selecting the ```2) Start a new network as a non-coordinator [WARNING: this clears everything]``` option, the other nodes still block. The main node keeps on reporting ad infinitum that nodes are joining the network:
```
... 
has joined the network
 has joined the network
 has joined the network
 has joined the network
 has joined the network
 has joined the network
 has joined the network
 has joined the network
 has joined the network
...
```

**Comment by coeniebeyers** [comment]
Hi! 

> The main node keeps on reporting that the nodes are joining, and frequently encounters errors when the same nodes attempt to join again.
This leads me to believe some ports aren't opened, specifically on the non-coordinating nodes. It seems like the coordinating node is able to receive messages from the non-coordinating nodes but not the other way around.

Can you give me more context about your setup? e.g. are these VMs in the cloud? Firewall rules?

Also, from your last post, it should be something like `raft2 has joined the network` where `raft2` was the name entered on the non-coordinating node.

I need to still add better running instructions, can you give me the exact sequence of menu options selected across the different nodes?

**Comment by coeniebeyers** [comment]
Also, `54.172.1.79 has joined the network with raftID: undefined` looks very wrong, instead of an ip address there should be the name entered by the non-coordinating node. Are you perhaps switching the entry of the node name and ip address ?

**Comment by bouwerp** [comment]
Thanks for the speedy reply!

Here is the sequence of my main node startup:
```
prompt: localIpAddress:  (129.232.226.18)
prompt: nodeName:
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  1
Please select an option below:
1) Start a new network as the coordinator [WARNING: this clears everything]
2) Start a new network as a non-coordinator [WARNING: this clears everything]
3) Join already running raft network [WARNING: this clears everything]
4) TODO: Start whisper services and attach to already running node
5) killall geth constellation-node
0) Quit
prompt: option:  1
Please select an option below:
1) Allow anyone to connect
2) [TODO] Allow only people with pre-auth tokens to connect
prompt: option:  1
[*] Starting new network...
Generating node key

enode: enode://16c73627c9156f33222b33a1fc2771de5541345329f55c6c5201245d38edd15ce56100eddc460c8cbca5d548c3382ef1e7aeb2147afaff0430a6ed4fbca6f5d6@129.232.226.18:20000?raftport=40000

[*] Starting communication network...
[*] New communication network started
Please wait for others to join. Hit any key + enter once done.
```

One of the child nodes:
```
Trying to get public ip address, please wait a few seconds...
Welcome!

Please enter the IP address other nodes will use to connect to this node.

Also, please enter a publicly identifyable string for this node to use.


prompt: localIpAddress: (54.83.184.40)
prompt: nodeName:
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option: 1
Please select an option below:
1) Start a new network as the coordinator [WARNING: this clears everything]
2) Start a new network as a non-coordinator [WARNING: this clears everything]
3) Join already running raft network [WARNING: this clears everything]
4) TODO: Start whisper services and attach to already running node
5) killall geth constellation-node
0) Quit
prompt: option: 3
In order to join the network, please enter the ip address of the coordinating node
prompt: ipAddress: 129.232.226.18
[*] Joining communication network...
true
[*] Communication network started
[*] Starting new network...
Generating node key

enode: enode://744249bd98402744b63cd1fa11302b91892e72a692cfbc2cc493646ca8bb6513d4d6ff3b5fcbcf8996f0d793928d45cee9771d9639d9f3522291758217896536@54.83.184.40:20000?raftport=40000

[*] Requesting existing network membership. This will block until the other node responds
```

**Comment by coeniebeyers** [comment]
Hi! No problem :) 

> prompt: nodeName:

I think that is the problem, you need to enter a name there like:

> prompt: nodeName: raft1

**Comment by bouwerp** [comment]
Still getting the same errors:
```
prompt: option:  raft1 has joined the network with raftID: 2
raft2 has joined the network with raftID: 2
raft1 has joined the network with raftID: 2
raft1 has joined the network with raftID: 2
raft1 has joined the network with raftID: 2
raft2 has joined the network with raftID: 2
raft2 has joined the network with raftID: 2
raft2 has joined the network with raftID: 2
raft2 has joined the network with raftID: 3
addPeer ERROR: Error: node is already in the cluster: enode://8f131497056c01cc2494fe5d3d3dff352a631bcde5ca623225a0f85d4011f81fae6712e03ad00347e68611b486428b4a787374318867f8f14e8ea856cbd5cb81@54.83.184.40:20000?raftport=40000
    at Object.InvalidResponse (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/errors.js:38:16)
    at /root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/httpprovider.js:122:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
raft1 has joined the network with raftID: undefined
raft2 has joined the network with raftID: 3
addPeer ERROR: Error: node is already in the cluster: enode://8f131497056c01cc2494fe5d3d3dff352a631bcde5ca623225a0f85d4011f81fae6712e03ad00347e68611b486428b4a787374318867f8f14e8ea856cbd5cb81@54.83.184.40:20000?raftport=40000
    at Object.InvalidResponse (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/errors.js:38:16)
    at /root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/web3quorum/lib/web3/httpprovider.js:122:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
raft1 has joined the network with raftID: undefined
readline.js:1017
            throw err;
            ^

TypeError: Cannot read property 'option' of undefined
    at /root/QuorumNetworkManager/QuorumNetworkManager/index.js:138:14
    at /root/QuorumNetworkManager/QuorumNetworkManager/node_modules/prompt/lib/prompt.js:336:20
    at /root/QuorumNetworkManager/QuorumNetworkManager/node_modules/prompt/node_modules/async/lib/async.js:148:21
    at assembler (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/prompt/lib/prompt.js:302:18)
    at /root/QuorumNetworkManager/QuorumNetworkManager/node_modules/prompt/lib/prompt.js:342:20
    at /root/QuorumNetworkManager/QuorumNetworkManager/node_modules/prompt/lib/prompt.js:542:14
    at onError (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/prompt/node_modules/read/lib/read.js:94:12)
    at Interface.<anonymous> (/root/QuorumNetworkManager/QuorumNetworkManager/node_modules/prompt/node_modules/read/lib/read.js:66:5)
    at emitNone (events.js:105:13)
    at Interface.emit (events.js:207:7)
```

I assigned names _raft1_ and _raft2_ for the other nodes, and _main_ for the main node.

What is the difference between options `2) Start a new network as a non-coordinator [WARNING: this clears everything]' and
`3) Join already running raft network [WARNING: this clears everything]`?

**Comment by coeniebeyers** [comment]
Hi! Atleast that is looking better. Can you do a `ps -ef | grep geth` ? I think there might be multiple geth instances still running. When you start `node index.js`, select option `5` to make sure you are starting on a clean slate.

**Comment by bouwerp** [comment]
Main, raft1 and raft2 seem to be geth-less. I saw that multiple constellation instances were still running, but I killed those too.

Let me try starting from scratch to see if I screwed something up.

**Comment by coeniebeyers** [comment]
> What is the difference between options 2) Start a new network as a non-coordinator [WARNING: this clears everything]' and3) Join already running raft network [WARNING: this clears everything]`?

I'll add more on the differences in the documentation shortly. 

The main differences are that option 2 is used by non-coordinating nodes while the coordinating node is still waiting for others to join. That is, before hitting any key + enter as per the main node:

```
Please wait for others to join. Hit any key + enter once done.
prompt: done:
```

Please note that you need to `hit any key + enter` once your other nodes have joined and they are blocking after 
```
[*] Requesting existing network membership. This will block until the other node responds
```

Option 3 is used by other nodes that weren't part of this "initial setup". That is, after you have continued on by `hit any key + enter` on your main node, and you have another node that wants to join, you can use option 3 for them join the network.

**Comment by bouwerp** [comment]
Thanks @coeniebeyers - I managed to get it working by having all the nodes on AWS, and the firewall configuration a little bit more under control. There seems to have been a network issue with the Hetzner machine.

**Comment by coeniebeyers** [comment]
Glad you came right! Note that I have now added [Starting a raft network](https://github.com/ConsenSys/QuorumNetworkManager/blob/master/README.md#starting-a-raft-network) which will hopefully be of future use.

**Comment by bouwerp** [comment]
Thanks @coeniebeyers - keep up the good work. This is awesome.
