### ISSUE TITLE
Sort out intermittent RPC connect issue

### ISSUE THREAD

**Issue by coeniebeyers** [ConsenSys/QuorumNetworkManager#71]
The following error happens intermittently. This might need an upgrade of web3, which unfortunately also requires all whisper work to be redone.

ERROR: Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/coenie/workspace/QuorumNetworkManager/test/node1/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/home/coenie/workspace/QuorumNetworkManager/test/node1/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/coenie/workspace/QuorumNetworkManager/test/node1/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/coenie/workspace/QuorumNetworkManager/test/node1/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/home/coenie/workspace/QuorumNetworkManager/test/node1/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/home/coenie/workspace/QuorumNetworkManager/test/node1/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by coeniebeyers** [comment]
This likely depends on #71

**Comment by Vinshu** [comment]
Hi,

How do you solve it, I am having the same issue?

**Comment by coeniebeyers** [comment]
Hi! Which version on the QNM are you using?
