### ISSUE TITLE
ERROR: Error: The method shh_newFilter does not exist/is not available 

### ISSUE THREAD

**Issue by simonmullaney** [ConsenSys/QuorumNetworkManager#94]
simon@Node4:~/workspace/QuorumNetworkManager$ node index.js
Trying to get public ip address, please wait a few seconds...
Welcome! 

Please enter the IP address other nodes will use to connect to this node. 

Also, please enter a publicly identifyable string for this node to use.

prompt: localIpAddress:  (13.92.188.92) 
prompt: nodeName:  node
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  5
ERROR: geth: no process found

geth: no process found

ERROR: constellation-node: no process found

constellation-node: no process found

Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  1
Please select an option below:
----- Option 1 and 2 are for the initial setup of a raft network -----
1) Start a node as the setup coordinator [Ideally there should only be one coordinator]
2) Start a node as a non-coordinator
----- Option 3 is for joining a raft network post initial setup  -----
3) Join a raft network if you were not part of the initial setup
4) TODO: Start whisper services and attach to already running node
5) killall geth constellation-node
0) Quit
prompt: option:  1
Please select an option below:
1) Allow anyone to connect
2) [TODO] Allow only people with pre-auth tokens to connect
prompt: option:  1
Please select an option below:
1) Clear all files/configuration and start from scratch[WARNING: this clears everything]
2) Keep old files/configuration intact and start the node + whisper services
prompt: option:  1
[*] Starting new node...
Generating node key

enode: enode://0785b5875d7a415f996893da13912f93ce42c290edde05528be20de439c52f650f1605005ff0ac365e8f2c7c7332dafd02e63a6f60b92ffb0a3a85129498279f@13.92.188.92:20000?raftport=40000

[*] Starting communication node...
[*] RPC connection established, Node started
Please wait for others to join. Hit any key + enter once done.
prompt: done:  ERROR: Error: The method shh_newFilter does not exist/is not available
    at Object.InvalidResponse (/home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/errors.js:38:16)
    at /home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
ERROR: Error: The method shh_newFilter does not exist/is not available
    at Object.InvalidResponse (/home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/errors.js:38:16)
    at /home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
ERROR: Error: The method shh_newFilter does not exist/is not available
    at Object.InvalidResponse (/home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/errors.js:38:16)
    at /home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/home/simon/workspace/QuorumNetworkManager/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/simon/workspace/QuorumNetworkManager/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)

[*] Creating genesis config...
[*] Starting raft node...

CommunicationNode.log:

WARN [10-19|10:06:48] No etherbase set and no accounts found as default
INFO [10-19|10:06:48] Starting peer-to-peer node               instance=Geth/v1.7.3-unstable-eea996e4/linux-amd64/go1.9.1
INFO [10-19|10:06:48] Allocated cache and file handles         database=/home/simon/workspace/QuorumNetworkManager/CommunicationNode/geth/chaindata cache=128 handles=1024
INFO [10-19|10:06:48] Writing default main-net genesis block
INFO [10-19|10:06:49] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}"
INFO [10-19|10:06:49] Disk storage enabled for ethash caches   dir=/home/simon/workspace/QuorumNetworkManager/CommunicationNode/geth/ethash count=3
INFO [10-19|10:06:49] Disk storage enabled for ethash DAGs     dir=/home/simon/.ethash                                                      count=2
INFO [10-19|10:06:49] Initialising Ethereum protocol           versions="[63 62]" network=91350
INFO [10-19|10:06:49] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [10-19|10:06:49] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [10-19|10:06:49] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [10-19|10:06:49] Regenerated local transaction journal    transactions=0 accounts=0
INFO [10-19|10:06:49] Starting P2P networking
INFO [10-19|10:06:49] started whisper v.5.0
INFO [10-19|10:06:49] HTTP endpoint opened: http://0.0.0.0:50010
INFO [10-19|10:06:49] RLPx listener up                         self="enode://9443bd2c5ccc5978831088755491417fe0c3866537b5e9638bcb6ad34cb9bcc58a9338bb492590ff200a54b43a6a03e4a7e33fa111d0a7f6b7192d1ca050f300@[::]:50000?discport=0"
INFO [10-19|10:06:49] IPC endpoint opened: /home/simon/workspace/QuorumNetworkManager/CommunicationNode/geth.ipc
INFO [10-19|10:09:19] Got interrupt, shutting down...
INFO [10-19|10:09:19] HTTP endpoint closed: http://0.0.0.0:50010
INFO [10-19|10:09:19] IPC endpoint closed: /home/simon/workspace/QuorumNetworkManager/CommunicationNode/geth.ipc
INFO [10-19|10:09:19] Blockchain manager stopped
INFO [10-19|10:09:19] Stopping Ethereum protocol
INFO [10-19|10:09:19] Ethereum protocol stopped
INFO [10-19|10:09:19] Transaction pool stopped
INFO [10-19|10:09:19] Database closed                          database=/home/simon/workspace/QuorumNetworkManager/CommunicationNode/geth/chaindata
INFO [10-19|10:09:19] whisper stopped

**Comment by coeniebeyers** [comment]
Hi! This is due to incompatible versions of web3 and geth 1.6. Which version of web3 and which branch of quorum are you using? 

There is an upgrade underway to move from whisper v2 (web3 versions smaller than 1, and geth 1.5 based) to whisper v5 (web3 versions greater than 1 and geth 1.6 +)

**Comment by simonmullaney** [comment]
Ok, is there any workaround for the time being?

I'm using:

Geth
Version: 1.7.3-unstable
Git Commit: eea996e4e1820d32a8ec82b03ff6bd17574770e7
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.1
Operating System: linux

 web3@1.0.0-beta.23

**Comment by coeniebeyers** [comment]
Hi! Unfortunately not yet no, the QNM is still busy being upgraded to web3 version 1+ and geth 1.6+

**Comment by simonmullaney** [comment]
Ok no worries :) Are there any versions of web3 and geth that work together? Can I not just get those versions and get it working that way no?

**Comment by coeniebeyers** [comment]
Hi! Absolutely, installing quorum from the master branch, as well as web3 0.19 should fix these issues. Hopefully the QNM shouldn't take long to catch up.

**Comment by caleteeter** [comment]
Same issue here.  @coeniebeyers the package with QNM now is web3 0.19 and the geth version in master branch of Quorum is 1.7.2-stable-1db4ecdc.  Which versions should we be using to get the coordinators to start without whisper errors.

**Comment by coeniebeyers** [comment]
On which branch are you guys? The latest commit on master of https://github.com/jpmorganchase/quorum/commits/master is `949b5c0d7b987b1881a68c28035d978e49fbb5ce`

Building against this commit, I get the following:
```
$geth version
Geth
Version: 1.5.0-unstable
Git Commit: 949b5c0d7b987b1881a68c28035d978e49fbb5ce
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
OS: linux
GOPATH=
GOROOT=/usr/local/go
```
This is also the commit that the `setup.sh` script of the QNM currently uses.

I can also confirm that I can start a node without any whisper errors

**Comment by simonmullaney** [comment]
Thanks  @coeniebeyers - I'm using the exact same as you :)

Geth
Version: 1.5.0-unstable
Git Commit: 949b5c0d7b987b1881a68c28035d978e49fbb5ce
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
OS: linux
GOPATH=
GOROOT=/usr/local/go
