### ISSUE TITLE
Failure to recreate coordinator node

### ISSUE THREAD

**Issue by conor10** [ConsenSys/QuorumNetworkManager#97]
My coordinator node was stopped, and I'm trying to bring it back up using its previous configuration.

The Geth & Constellation nodes start back up, however, an exception is thrown, and QNM exits. Console output is below.

```
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  1
Please select an option below:
----- Option 1 and 2 are for the initial setup of a raft network -----
1) Start a node as the setup coordinator [Ideally there should only be one coordinator]
2) Start a node as a non-coordinator
----- Option 3 is for joining a raft network post initial setup  -----
3) Join a raft network if you were not part of the initial setup
4) TODO: Start whisper services and attach to already running node
5) Kill all geth constellation-node
0) Quit
prompt: option:  1
Please select an option below:
1) Allow anyone to connect
2) [TODO] Allow only people with pre-auth tokens to connect
prompt: option:  1
Please select an option below:
1) Clear all files/configuration and start from scratch[WARNING: this clears everything]
2) Keep old files/configuration intact and start the node + whisper services
prompt: option:  2
[*] Starting new node...
[*] Starting communication node...
[*] RPC connection established, Node started
[*] Starting raft node...
waiting for RPC connection ...
waiting for RPC connection ...
[*] RPC connection established, Node started
/home/ubuntu/workspace/QuorumNetworkManager/Communication/nodeInformation.js:27
    address: result.addressList[0],
                               ^

TypeError: Cannot read property '0' of undefined
    at publishNodeInformation (/home/ubuntu/workspace/QuorumNetworkManager/Communication/nodeInformation.js:27:32)
    at /home/ubuntu/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2550:16
    at /home/ubuntu/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2489:9
    at replenish (/home/ubuntu/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/home/ubuntu/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:931:17)
    at /home/ubuntu/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:906:16
    at /home/ubuntu/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2491:13
    at /home/ubuntu/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2552:17
    at existingRaftNetworkMembership (/home/ubuntu/workspace/QuorumNetworkManager/Communication/networkMembership.js:210:3)
    at /home/ubuntu/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2550:16
```

**Comment by coeniebeyers** [comment]
Hi! Apologies, this was introduced when adding the nodeInformation functionality. Should be fixed in https://github.com/ConsenSys/QuorumNetworkManager/commit/b85bbb447df0a8e1c0370a1a394cd2377f4103ce

**Comment by conor10** [comment]
Thanks, looks ok now.
